version: '2'
services:
    postgres:
        image: jose/bdatividajsf
        build: ./database
        container_name: bancoatividadejsf
        ports:
          - "5433:5432" 
    web:
        image: jose/atividajsf
        build: ./app
        container_name: appatividadejsf
        ports:
          - "8082:8080"
        links:
          - "postgres:host-banco" 
  
